#########################################################################
# Title:         Saltbox: Sanity Check | Python Version                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Python Version | Print Python version
  ansible.builtin.debug:
    msg: "Ansible running on Python version: {{ ansible_python_version }}"

- name: Python Version | Fail if Ansible is using '/usr/bin/python3' as the Python interpreter
  ansible.builtin.fail:
    msg: "Run 'sb install settings' to upgrade your ansible.cfg"
  when: ansible_python.executable == '/usr/bin/python3'
