---
- hosts: localhost # noqa name[play]
  module_defaults:
    ansible.builtin.setup:
      fact_path: "/srv/git/saltbox/ansible_facts.d"
  vars_files:
    - ['accounts.yml', 'defaults/accounts.yml.default']
    - ['settings.yml', 'defaults/settings.yml.default']
    - ['adv_settings.yml', 'defaults/adv_settings.yml.default']
    - ['backup_config.yml', 'defaults/backup_config.yml.default']
    - ['providers.yml', 'defaults/providers.yml.default']
  roles:
    - { role: settings, tags: ['settings'] }
    - { role: pre_tasks, tags: ['always', 'pre-tasks'] }
    - { role: sanity_check, tags: ['sanity-check'] }
    - { role: backup, tags: ['backup'] }
    - { role: backup2, tags: ['backup2'] }
    - { role: restore, tags: ['restore'] }
    # Core
    - { role: kernel, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'preinstall', 'kernel'] }
    - { role: hetzner, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'preinstall', 'hetzner'] }
    - { role: user, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'preinstall', 'user'] }
    - { role: shell, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'preinstall', 'shell'] }
    - { role: rclone, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'preinstall', 'rclone'] }
    - { role: system, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'system'] }
    - { role: common, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'common'] }
    - { role: motd, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'motd'] }
    - { role: mount_templates, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'mounts', 'mount-templates'] }
    - { role: remote, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'mounts'] }
    - { role: unionfs, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'mounts'] }
    - { role: docker, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'docker', 'docker-filesystem-resize'] }
    - { role: nvidia, tags: ['core', 'saltbox', 'mediabox', 'nvidia'], when: ['use_nvidia'] }
    - { role: scripts, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'scripts'] }
    - { role: sandbox, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'sandbox'] }
    - { role: traefik, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'traefik', 'traefik-reset-certs'] }
    - { role: cloudflare, tags: ['core', 'saltbox', 'mediabox', 'feederbox', 'cloudflare'], when: ['cloudflare_is_enabled'] }
    # Apps Start
    - { role: media_server, tags: ['saltbox', 'mediabox', 'media-server'] }
    - { role: download_clients, tags: ['saltbox', 'feederbox', 'download-clients'] }
    - { role: download_indexers, tags: ['saltbox', 'feederbox', 'download-indexers'] }
    - { role: tautulli, tags: ['saltbox', 'mediabox', 'tautulli'] }
    - { role: overseerr, tags: ['saltbox', 'mediabox', 'overseerr'] }
    - { role: portainer, tags: ['saltbox', 'feederbox', 'portainer'] }
    - { role: organizr, tags: ['saltbox', 'feederbox', 'organizr'] }
    - { role: cloudplow, tags: ['saltbox', 'feederbox', 'cloudplow', 'cloudplow-reset'], when: ['use_cloudplow'] }
    - { role: sonarr, tags: ['saltbox', 'feederbox', 'sonarr'] }
    - { role: radarr, tags: ['saltbox', 'feederbox', 'radarr'] }
    - { role: lidarr, tags: ['saltbox', 'feederbox', 'lidarr'] }
    - { role: iperf3, tags: ['saltbox', 'mediabox', 'feederbox', 'iperf3'] }
    - { role: nethogs, tags: ['saltbox', 'mediabox', 'feederbox', 'nethogs'] }
    - { role: glances, tags: ['saltbox', 'mediabox', 'feederbox', 'glances'] }
    - { role: btop, tags: ['saltbox', 'mediabox', 'feederbox', 'btop'] }
    - { role: asshama, tags: ['asshama'] }
    - { role: arr_db, tags: ['arr-db'] }
    - { role: authelia, tags: ['authelia', 'authelia-reset', 'lldap-reset'] }
    - { role: autobrr, tags: ['autobrr'] }
    - { role: autoheal, tags: ['autoheal'] }
    - { role: autoscan, tags: ['autoscan'] }
    - { role: bazarr, tags: ['bazarr'] }
    - { role: btrfsmaintenance, tags: ['btrfsmaintenance'] }
    - { role: cadvisor, tags: ['cadvisor'] }
    - { role: ddclient, tags: ['ddclient'] }
    - { role: ddns, tags: ['ddns'] }
    - { role: deluge, tags: ['deluge'] }
    - { role: diun, tags: ['diun'] }
    - { role: docker_socket_proxy, tags: ['docker-socket-proxy'] }
    - { role: dozzle, tags: ['dozzle'] }
    - { role: emby, tags: ['emby'] }
    - { role: gluetun, tags: ['gluetun'] }
    - { role: grafana, tags: ['grafana'] }
    - { role: jackett, tags: ['jackett'] }
    - { role: jellyfin, tags: ['jellyfin'] }
    - { role: mainline, tags: ['mainline'] }
    - { role: mariadb, tags: ['mariadb'] }
    - { role: mongodb, tags: ['mongodb'] }
    - { role: netdata, tags: ['netdata'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: node_exporter, tags: ['node-exporter'] }
    - { role: nzbget, tags: ['nzbget'] }
    - { role: nzbhydra2, tags: ['nzbhydra2'] }
    - { role: nzbthrottle, tags: ['nzbthrottle'] }
    - { role: petio, tags: ['petio'] }
    - { role: plex, tags: ['plex', 'plex-reset-codecs'] }
    - { role: plex_db, tags: ['plex-db'] }
    - { role: postgres, tags: ['postgres'] }
    - { role: prometheus, tags: ['prometheus'] }
    - { role: prowlarr, tags: ['prowlarr'] }
    - { role: python, tags: ['python'] }
    - { role: qbittorrent, tags: ['qbittorrent'] }
    - { role: readarr, tags: ['readarr'] }
    - { role: redis, tags: ['redis'] }
    - { role: rutorrent, tags: ['rutorrent'] }
    - { role: sabnzbd, tags: ['sabnzbd'] }
    - { role: subliminal, tags: ['subliminal'] }
    - { role: traktarr, tags: ['traktarr'] }
    - { role: transfer, tags: ['transfer'] }
    - { role: unpackerr, tags: ['unpackerr'] }
    - { role: whisparr, tags: ['whisparr'] }
    - { role: yyq, tags: ['yyq'] }
    # Apps End
    - { role: custom, tags: ['custom'] }
    - { role: hetzner_nfs, tags: ['hetzner-nfs-server', 'hetzner-nfs-server-uninstall', 'hetzner-nfs-client-mount', 'hetzner-nfs-client-unmount'] }
    - { role: plex_auth_token, tags: ['plex-auth-token'] }
    - { role: plex_extra_tasks, tags: ['plex-extra-tasks'] }
    - { role: sub_zero, tags: ['plex-plugins-sub-zero', 'plex-plugins-sub-zero-reinstall'] }
    - { role: webtools, tags: ['plex-plugins-webtools', 'plex-plugins-webtools-reinstall'] }
    - { role: saltbox_mod, tags: ['saltbox_mod'] }
