#########################################################################
# Title:         Saltbox: Nvidia | nvtop Tasks                          #
# Author(s):     desimaniac, l3uddz, salty                              #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: nvtop | Install gnupg Dependencies
  ansible.builtin.apt:
    name: dirmngr

- name: nvtop | Add flexiondotorg apt key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 824A27DD09DEDA33BF7835962EA8F35793D8809A
    keyring: /usr/share/keyrings/flexiondotorg.gpg

- name: nvtop | Add flexiondotorg/nvtop repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/flexiondotorg.gpg] http://ppa.launchpad.net/flexiondotorg/nvtop/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    filename: "flexiondotorg"
    state: present
    update_cache: true

- name: nvtop | Install nvtop
  ansible.builtin.apt:
    name: nvtop
    state: present

- name: nvtop | Get nvtop binary version
  ansible.builtin.shell: "{{ nvidia_nvtop_binary_version_lookup_command }}"
  register: nvtop_binary_version
  ignore_errors: true

- name: nvtop | Display nvtop binary version
  ansible.builtin.debug:
    msg: "nvtop {{ nvtop_binary_version.stdout }} installed."
