#########################################################################
# Title:         Saltbox: NZBHydra2 | Settings Task                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Settings | Wait for config file to be created
  ansible.builtin.wait_for:
    path: "{{ nzbhydra2_paths_config_location }}"
    state: present

- name: Wait 30 seconds
  ansible.builtin.wait_for:
    timeout: 30

- name: Post-Install | Settings | Stop container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"

- name: Post-Install | Settings | Update settings
  ansible.builtin.shell: |
    yyq e -i '{{ item }}' {{ nzbhydra2_paths_config_location }}
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ nzbhydra2_config_settings_list }}"

- name: Post-Install | Settings | Start container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
