##########################################################################
# Title:         Saltbox: Remote | Default Variables                     #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Global
################################

user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

rclone_config_path: "/home/{{ user.name }}/.config/rclone/rclone.conf"
rclone_vfs_cache_dir: ""
rclone_vfs_cache_dir_lookup: "{{ lookup('vars', 'rclone_remote_' + item.remote + '_vfs_cache_dir', default=rclone_vfs_cache_dir) }}"
rclone_vfs_cache_min_free_space: "off"
rclone_vfs_cache_poll_interval: "1m0s"
rclone_cloud_dir_cache_time: "8760h"
rclone_sftp_dir_cache_time: "1m"
rclone_sftp_disable_hashcheck: false
rclone_service_template: "saltbox_managed_rclone_"

rclone_port_lookup: "{{ port_lookup_rclone.meta.port
                        if (port_lookup_rclone.meta.port is defined) and (port_lookup_rclone.meta.port | trim | length > 0)
                        else '5572' }}"
rclone_remort_port: "{{ lookup('vars', 'rclone_remote_' + item.remote + '_port', default=rclone_port_lookup) }}"
rclone_remote_name: "{{ item.remote.split(':')[0] if ':' in item.remote else item.remote }}"
rclone_remote_with_path: "{{ item.remote if ':' in item.remote else item.remote + ':' }}"
rclone_first_remote_name: "{{ rclone.remotes[0].remote.split(':')[0] if ':' in rclone.remotes[0].remote else rclone.remotes[0].remote }}"
rclone_first_remote_name_with_path: "{{ rclone.remotes[0].remote if ':' in rclone.remotes[0].remote else rclone.remotes[0].remote + ':Media' }}"

remote_update_rclone: true

################################
# Rclone VFS Refresh
################################

rclone_vfs_refresh_interval: 10800
rclone_vfs_refresh_command: |-
  /usr/bin/rclone rc vfs/refresh recursive=true --url http://localhost:{{ rclone_remort_port }} _async=true

################################
# NFS
################################

nfs_opts: "nofail,noatime,nolock,intr,tcp,actimeo=1800"
