#########################################################################
# Title:         Saltbox: Emby | Settings Task                          #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config file to be created
  ansible.builtin.wait_for:
    path: "{{ emby_paths_config_location }}"
    state: present

- name: Settings | Stop Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/stop_docker_container.yml"

- name: Settings | Update config file
  community.general.xml:
    path: "{{ emby_paths_config_location }}"
    xpath: "/ServerConfiguration/{{ item.xpath }}"
    value: "{{ item.value }}"
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ emby_config_settings_list }}"

- name: Settings | Start Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/start_docker_container.yml"
