#########################################################################
# Title:         Saltbox: UnionFS | Docker | Daemon Tasks               #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Docker | Daemon | Set '_remotes_list' variable
  ansible.builtin.set_fact:
    _remotes_services_list: "{{ _remotes_services_list | default('') + (rclone_service_template + rclone_remote_name + '.service ') }}"
  with_items: "{{ rclone.remotes }}"
  when: rclone_remote_is_defined and use_remote and item.template != "nfs"

- name: "Docker | Daemon | Create override directory"
  ansible.builtin.file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    mode: "0775"

- name: "Docker | Daemon | Import override file"
  ansible.builtin.template:
    src: "roles/docker/templates/override.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/override.conf"
    mode: "0644"
    force: "{{ docker_service_force }}"

- name: "Docker | Daemon | Tasks for when Docker was stopped by Remote role"
  when: remote_stopped_docker
  block:
    - name: "Docker | Daemon | Start docker service"
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
        daemon_reload: true

    - name: "Docker | Daemon | Wait for 30 seconds before commencing"
      ansible.builtin.wait_for:
        timeout: 30
