#########################################################################
# Title:         Saltbox: Resources | Tasks | DNS | Tasker              #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Resources | Tasks | DNS | Tasker | Import
  ansible.builtin.include_tasks: "tasker2.yml"
  when: cloudflare_records_enabled and role_dns_enabled and not skip_dns
