#########################################################################
# Title:         Saltbox: Docker | Compose Switch Tasks                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Compose Switch | Cleanup Compose Switch"
  when: compose_cleanup_switch
  block:
    - name: "Compose Switch | Check if '/usr/local/bin/compose-switch' exists"
      ansible.builtin.stat:
        path: '/usr/local/bin/compose-switch'
      register: compose_switch_cleanup_path

    - name: "Compose Switch | Run tasks if '/usr/local/bin/compose-switch' exists"
      when: compose_switch_cleanup_path.stat.exists
      block:
        - name: "Compose Switch | Remove docker-compose alternatives"
          ansible.builtin.shell: update-alternatives --remove-all docker-compose
          ignore_errors: true

        - name: "Compose Switch | Delete '/usr/local/bin/compose-switch'"
          ansible.builtin.file:
            dest: "/usr/local/bin/compose-switch"
            state: absent

        - name: "Compose Switch | Delete '/usr/local/bin/docker-compose-v1'"
          ansible.builtin.file:
            dest: "/usr/local/bin/docker-compose-v1"
            state: absent
