#########################################################################
# Title:         Saltbox: Docker | Binary Tasks                         #
# Author(s):     desimaniac, l3uddz, salty                              #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Binary | Add official gpg signing key to trusted.gpg.d
  ansible.builtin.get_url:
    url: "{{ docker_apt_key_url }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: "0644"
  register: result
  retries: "{{ '0' if (not continuous_integration) else '5' }}"
  delay: 10
  until: result is succeeded

- name: Binary | Remove old official repository entries
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    filename: "{{ docker_apt_repo_filename }}"
    update_cache: true
    state: absent
  loop:
    - "{{ docker_apt_repo_url_old }}"
    - "{{ docker_apt_repo_url_old2 }}"

- name: Binary | Add official repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    filename: "{{ docker_apt_repo_filename }}"
    update_cache: true
  register: result
  retries: "{{ '0' if (not continuous_integration) else '5' }}"
  delay: 10
  until: result is succeeded

- name: Binary | Install Docker binaries
  ansible.builtin.include_tasks: "binary2.yml"
  loop:
    - 'containerd_io'
    - 'docker_ce'
    - 'docker_ce_cli'
    - 'compose_cli'
    - 'docker_rootless'

- name: Binary | Install apparmor
  ansible.builtin.apt:
    name:
      - apparmor
