########################################################################################
# Title:         Saltbox: Settings | Migrator | 'settings.yml' | Migration 01          #
# Author(s):     salty                                                                 #
# URL:           https://github.com/saltyorg/Saltbox                                   #
# --                                                                                   #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################

---
- name: "Migrator | 'settings.yml' | Migration 01 | Set variables"
  ansible.builtin.set_fact:
    old_download: "{{ not
                      ((downloads.nzbs is undefined)
                      or
                      (downloads.torrents is undefined)) }}"
    old_feeder_mount: "{{ (not ((mounts.feeder is undefined)
                          or
                          (mounts.feeder is none)
                          or
                          (mounts.feeder | trim | length == 0)))
                          and mounts.feeder }}"

- name: Migrator | 'settings.yml' | Migration 01 | Rebuild 'downloads' dict
  ansible.builtin.shell: |
    yyq e -i 'del(.downloads)' {{ playbook_dir }}/{{ file }}
    yyq e -i '.downloads = "/mnt/unionfs/downloads"' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: old_download

- name: Migrator | 'settings.yml' | Migration 01 | Delete 'rclone.remote' dict
  ansible.builtin.shell: |
    yyq e -i 'del(.rclone.remote)' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: rclone.remote is defined

- name: Migrator | 'settings.yml' | Migration 01 | Create 'rclone.remotes' dict
  ansible.builtin.shell: |
    yyq e -i '.rclone.remotes += [{"remote": "{{ rclone.remote }}", "template": "google", "upload": true, "upload_from": "/mnt/local/Media", "vfs_cache": {"enabled": false, "size": "50G", "max_age": "504h"}}]' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: (rclone.remotes is undefined) and rclone_old_remote_is_defined

- name: Migrator | 'settings.yml' | Migration 01 | Create 'rclone.remotes' dict
  ansible.builtin.shell: |
    yyq e -i '.rclone.remotes += [{"remote": "google", "template": "google", "upload": true, "upload_from": "/mnt/local/Media", "vfs_cache": {"enabled": false, "size": "50G", "max_age": "504h"}}]' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: (rclone.remotes is undefined) and not rclone_old_remote_is_defined

- name: Migrator | 'settings.yml' | Migration 01 | Add feeder to remotes
  ansible.builtin.shell: |
    yyq e -i '.rclone.remotes += [{"remote": "feeder", "template": "sftp", "upload": false, "upload_from": "/mnt/local/Media", "vfs_cache": {"enabled": false, "size": "50G", "max_age": "504h"}}]' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: old_feeder_mount

- name: Migrator | 'settings.yml' | Migration 01 | Create 'rclone.enabled' dict
  ansible.builtin.shell: |
    yyq e -i '.rclone.enabled = {{ "true" if (rclone_old_remote_is_defined or rclone_remote_is_defined) else "false" }}' {{ playbook_dir }}/{{ file }}
  become: true
  become_user: "{{ saltbox_yml.stat.pw_name }}"
  when: (rclone.enabled is undefined)

- name: Migrator | 'settings.yml' | Migration 01 | Remove 'null' values
  ansible.builtin.replace:
    path: "{{ playbook_dir }}/{{ file }}"
    regexp: '(?<=: )\bnull\s*$'
    replace: ''
    owner: "{{ saltbox_yml.stat.uid }}"
    group: "{{ saltbox_yml.stat.gid }}"
    mode: "0664"

- name: Migrator | 'settings.yml' | Migration 01 | Re-import Variables
  ansible.builtin.include_vars: "{{ playbook_dir }}/{{ file }}"
