#########################################################################
# Title:         Saltbox: Settings | Start                              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Start | Install ruamel.yaml"
  ansible.builtin.pip:
    name: ruamel.yaml
    state: "latest"

- name: "Start | Install yyq"
  ansible.builtin.include_role:
    name: yyq

- name: "Start | Get 'saltbox.yml' info"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/saltbox.yml"
  register: saltbox_yml

- name: "Start | Create list of config files"
  ansible.builtin.set_fact:
    config_files:
      - "ansible.cfg"
      - "accounts.yml"
      - "settings.yml"
      - "adv_settings.yml"
      - "backup_config.yml"
      - "providers.yml"
      - "hetzner_nfs.yml"
    traefik3_migration: "{{ true if (rclone.remotes is undefined) else false }}"

- name: Start | Initialize vars with empty lists
  ansible.builtin.set_fact:
    files_updated_successfully: []
    files_updated_unsuccessfully: []
    exit_is_necessary: false

- name: "Start | Check if 'settings-updater.log' exists"
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/settings-updater.log"
  register: settings_updater_log

- name: "Start | Reset ownership of 'settings-updater.log'"
  ansible.builtin.file:
    path: "{{ playbook_dir }}/settings-updater.log"
    state: file
    owner: "{{ saltbox_yml.stat.uid }}"
    group: "{{ saltbox_yml.stat.gid }}"
    mode: "0664"
  when: settings_updater_log.stat.exists
