##########################################################################
# Title:         Saltbox: UnionFS | Default Variables                    #
# Author(s):     desimaniac, salty                                       #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Global
################################

local_mount_branch: "/mnt/local=RW:"

custom_mount_branch: "" # Format: "/mnt/remote/someremote=NC"

mergerfs_override_service: true

mergerfs_service_name: "saltbox_managed_mergerfs.service"

################################
# MergerFS
################################

mergerfs_version: latest

mergerfs_github_endpoint: "{{ 'latest' if (mergerfs_version == 'latest') else 'tags/' + mergerfs_version }}"

mergerfs_releases_url: "{{ svm }}https://api.github.com/repos/trapexit/mergerfs/releases/{{ mergerfs_github_endpoint }}"

mergerfs_releases_download_url: https://github.com/trapexit/mergerfs/releases/download

mergerfs_release_distribution: "{{ ansible_distribution_release | lower }}"

mergerfs_release_lookup_command: |
  curl -s {{ mergerfs_releases_url }} \
    | jq -r ".assets[] | select(.name | test(\"{{ ansible_distribution | lower }}-{{ mergerfs_release_distribution }}_amd64\")) \
    | .browser_download_url"

mergerfs_download_backup_version: 2.35.0

mergerfs_download_backup_url: "
  {{ mergerfs_releases_download_url }}/\
  {{ mergerfs_download_backup_version }}/\
  mergerfs_{{ mergerfs_download_backup_version }}.\
  {{ ansible_distribution | lower }}-\
  {{ mergerfs_release_distribution }}_amd64.deb"

mergerfs_mount_branches: "{{ local_mount_branch }}{{ _remotes_list }}"

mergerfs_mount_service_after: "network-online.target"

mergerfs_mount_readdir_policy: "seq"

mergerfs_mount_start_command: |-
  /usr/bin/mergerfs \
    -o category.create=ff,async_read=true,cache.files=partial \
    -o dropcacheonclose=true,minfreespace=0,fsname=mergerfs \
    -o xattr=nosys,statfs=base,statfs_ignore=nc,umask=002,noatime \
    -o func.readdir={{ mergerfs_mount_readdir_policy }} \
    {{ mergerfs_mount_branches }} /mnt/unionfs

mergerfs_mount_stop_command: /bin/fusermount3 -uz /mnt/unionfs
